/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as InstallRouteImport } from './routes/install'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FramesCommentsRouteImport } from './routes/frames.comments'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FramesCommentsRoute = FramesCommentsRouteImport.update({
  id: '/frames/comments',
  path: '/frames/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/install': typeof InstallRoute
  '/settings': typeof SettingsRoute
  '/frames/comments': typeof FramesCommentsRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/install': typeof InstallRoute
  '/settings': typeof SettingsRoute
  '/frames/comments': typeof FramesCommentsRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/install': typeof InstallRoute
  '/settings': typeof SettingsRoute
  '/frames/comments': typeof FramesCommentsRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/editor' | '/install' | '/settings' | '/frames/comments' | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/editor' | '/install' | '/settings' | '/frames/comments' | '/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/install'
    | '/settings'
    | '/frames/comments'
    | '/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  InstallRoute: typeof InstallRoute
  SettingsRoute: typeof SettingsRoute
  FramesCommentsRoute: typeof FramesCommentsRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frames/comments': {
      id: '/frames/comments'
      path: '/frames/comments'
      fullPath: '/frames/comments'
      preLoaderRoute: typeof FramesCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  InstallRoute: InstallRoute,
  SettingsRoute: SettingsRoute,
  FramesCommentsRoute: FramesCommentsRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
